/* go_signal.c — Go signal deferral wrapper */
#include "signal_internal.h"
#include <signal.h>

/* ── Go signal deferral wrapper ────────────────────────────────
 * Go's signal handler (sigtrampgo) crashes if a signal arrives before
 * m.gsignal is allocated. We wrap Go's handler and defer signal delivery
 * until Go is ready.
 *
 * "Go ready" means the runtime can run sigtrampgo: tls_g points at a
 * live g, g.m points at a live m, AND m.curg is set. A signal that
 * arrives while m.curg is still NULL belongs to the boot path (rt0_go /
 * needm / systemstack), where sigtrampgo dereferences m.curg and faults
 * at address 0 — the m.curg=0 / rip=0 crash this wrapper exists to
 * prevent. Deferring until curg is set is what makes the difference.
 *
 * Field offsets come from the fetched upstream source, not memory:
 * docs/golang/runtime2.go-go1.26.4.txt
 *   type g struct { stack stack; stackguard0, stackguard1 uintptr;
 *                   _panic *_panic; _defer *_defer; m *m; ... }
 *     stack 0x00 (lo,hi) | stackguard0 0x10 | stackguard1 0x18
 *     _panic 0x20 | _defer 0x28 | m 0x30
 *   type m struct { g0 *g; morebuf gobuf; divmod uint32; procid uint64;
 *                   gsignal *g; goSigStack gsignalStack; ...
 *                   curg *g; ... }
 *     g0 0x00 | morebuf 0x08 (gobuf = 6 words) | divmod 0x38 (+4 pad)
 *     procid 0x40 | gsignal 0x48
 *
 * m.gsignal is checked only as "non-NULL"; its value is a gsignalStack
 * (Go-heap) on some builds, so it must never be treated as a guest g.
 * The offset that actually matters for readiness is m.curg. */

/* Saved Go signal handlers (indexed by Linux signal number). */
void *macify_saved_go_handlers[32] = {0};

static volatile int macify_go_signal_ready = 0;

/* m.curg offset — after gsignal/goSigStack/sigmask/tls/mstartfn. */
#define MACIFY_M_CURG_OFF 0xb8

/* Called by the wrapper to check if Go is ready for signals. */
static int go_is_ready(void) {
    if (macify_go_signal_ready) return 1;
    extern uint64_t g_tls_g_addr;
    if (g_tls_g_addr) {
        uint64_t g = *(volatile uint64_t *)g_tls_g_addr;
        if (g != 0) {
            /* g.m is at g+0x30 */
            uint64_t m = *(volatile uint64_t *)(g + 0x30);
            if (m != 0) {
                /* m.gsignal allocated (handler state exists) AND
                 * m.curg non-NULL (a g is actually running, so sigtrampgo
                 * will not fault on the stack switch). */
                uint64_t gsignal = *(volatile uint64_t *)(m + 0x48);
                uint64_t curg = *(volatile uint64_t *)(m + MACIFY_M_CURG_OFF);
                if (gsignal != 0 && curg != 0) {
                    macify_go_signal_ready = 1;
                    return 1;
                }
            }
        }
    }
    return 0;
}

void macify_go_signal_wrapper(int sig, siginfo_t *info, void *uctx) {
    if (getenv("MACIFY_TRACE_SIGNAL")) {
        char b[256]; int n = snprintf(b, sizeof(b), "macify: go_signal_wrapper(sig=%d) go_ready=%d handler=%p\n",
                sig, macify_go_signal_ready,
                (sig >= 0 && sig < 32) ? macify_saved_go_handlers[sig] : NULL);
        (void)write(2, b, n);
    }

    if (go_is_ready()) {
        /* Go is ready — call the saved Go handler */
        if (sig >= 0 && sig < 32 && macify_saved_go_handlers[sig]) {
            void (*go_handler)(int, siginfo_t *, void *) =
                (void (*)(int, siginfo_t *, void *))macify_saved_go_handlers[sig];
            if (getenv("MACIFY_TRACE_SIGNAL")) {
                char b[128]; int n = snprintf(b, sizeof(b),
                    "macify: calling Go handler sig=%d fn=%p\n", sig, go_handler);
                (void)write(2, b, n);
            }
            go_handler(sig, info, uctx);
            return;
        }
    } else {
        /* A SYNCHRONOUS fault must never be deferred.
         *
         * The boot-time SIGSEGV we see is generated by the guest's own
         * instruction (m.curg=0 → sigtrampgo dereferences NULL). Returning
         * from its handler re-executes that instruction, which faults
         * again, forever — an unkillable spin at 100% CPU rather than a
         * crash. Only signals the kernel sent on its own (kill, timer,
         * SIGURG preemption: SI_USER / SI_TIMER / SI_KERNEL) are safe to
         * hold, because nothing is waiting on the handler to make
         * progress.
         *
         * So: defer only non-synchronous signals. A synchronous fault with
         * Go not yet ready goes to the real crash handler, which reports
         * the faulting address and exits deterministically. */
        int sync_fault = 0;
        if (info) {
            switch (info->si_code) {
            case SI_USER: case SI_TKILL: case SI_QUEUE:
            case SI_TIMER:  case SI_SIGIO:  case SI_ASYNCIO:
            case SI_MESGQ:  case SI_KERNEL:
                break;                        /* async — safe to hold */
            default:
                sync_fault = 1;               /* SEGV_MAPERR/BUSERR/ILL_… */
                break;
            }
        } else {
            sync_fault = 1;
        }
        if (sync_fault) {
            if (getenv("MACIFY_TRACE_SIGNAL")) {
                char b[160]; int n = snprintf(b, sizeof(b),
                    "macify: Go NOT ready + sync fault (code=%d) sig=%d — reporting\n",
                    info ? info->si_code : -1, sig);
                (void)write(2, b, n);
            }
            extern void macify_crash_handler(int, siginfo_t *, void *);
            macify_crash_handler(sig, info, uctx);
            /* Not reached: macify_crash_handler exits. Return anyway so a
             * future non-exiting variant cannot spin. */
            return;
        }
        if (getenv("MACIFY_TRACE_SIGNAL")) {
            char b[128]; int n = snprintf(b, sizeof(b),
                "macify: Go NOT ready, deferring sig=%d\n", sig);
            (void)write(2, b, n);
        }
    }
    /* Go is NOT ready — defer the signal by re-blocking it.
     * The signal will be re-delivered when Go unblocks it via sigprocmask.
     * CRITICAL: use the real glibc sigset_t (128 bytes), not the 4-byte
     * macOS sigset. Our sigemptyset/sigaddset overrides write only 4 bytes,
     * leaving 124 bytes uninitialized — glibc reads all 128 bytes. */
    sigset_t mask;
    /* Manually zero the entire 128-byte sigset, then set the bit */
    memset(&mask, 0, sizeof(mask));
    /* Use the real glibc sigaddset, not our override (which writes only 4 bytes) */
    static int (*real_sigaddset_glibc)(sigset_t *, int) = NULL;
    if (!real_sigaddset_glibc) real_sigaddset_glibc = macify_elf_lookup("sigaddset");
    if (real_sigaddset_glibc) {
        real_sigaddset_glibc(&mask, sig);
    } else {
        /* Fallback: set bit manually using glibc's bit layout (sig - 1) */
        unsigned long *bits = (unsigned long *)&mask;
        bits[(sig - 1) / (sizeof(unsigned long) * 8)] |= (1UL << ((sig - 1) % (sizeof(unsigned long) * 8)));
    }
    /* Call glibc's sigprocmask directly (bypass our override which might
     * mistranslate when called from the shim). */
    static int (*real_sigprocmask_glibc)(int, const sigset_t *, sigset_t *) = NULL;
    if (!real_sigprocmask_glibc) real_sigprocmask_glibc = macify_elf_lookup("sigprocmask");
    if (real_sigprocmask_glibc) {
        real_sigprocmask_glibc(SIG_BLOCK, &mask, NULL);
    }
}
